```{r data generation, echo = FALSE, results = 'hide'}
## DATA GENERATION

library(imputeTS)

ts <- tsAirgap

mask <- is.na(ts)

ts1 <- na_kalman(ts, 
              model = 'auto.arima')

ts2 <- na_interpolation(ts)

sol_round <- round(abs(mean(ts1[mask]-ts2[mask])),3)


```

Question
========

Consider tsAirgap dataset on monthly totals of international airline passengers with missing values. You need to fill in the missing data using  (1) Kalman Filtering based on ARIMA model with automatically chosen parameters and (2) linear interpolation. Provide the absolute value of mean difference of the imputed values rounded with 3 decimal digits as an answer.


You can load the tsAirgap data set in R by issuing the following command at the console data("tsAirgap") after importing "imputeTS" library or if you use other programming languages you can download it [here](https://github.com/SteffenMoritz/imputeTS/blob/master/data/tsAirgap.rda).



Solution
========

You can use na_kalman(ts, model = 'auto.arima') and na_interpolation(ts) function.

Meta-information
================
exname:  Processing 1
extype: num
exsolution: `r sol_round`
extol: 0.01