```{r data generation, echo = FALSE, results = 'hide'}
## DATA GENERATION

library(tibble)
library(dplyr)
library(imputeTS)
library(anomalize) 
library(lubridate)

ts <- tsAirgap
ts2 <- na_interpolation(ts)
true37 <- ts2[37]

ts2[37] <- 0
ts2 <- tibble(ts2  = ts2 )

n = nrow(ts2)
ts2 = mutate(ts2, date = ymd('1949-01-01') +
                months(0:(n - 1)))

decomp <- time_decompose(ts2,ts2)
decomp <- anomalize(decomp, target = remainder)
decomp <- time_recompose(decomp)
decomp <- clean_anomalies(decomp)


sol_round <- round(abs(decomp$observed_cleaned[37]-true37),3)


```

Question
========

Consider tsAirgap dataset on monthly totals of international airline passengers with missing values filled in with linear interpolation. 

Let's say 37th observation of that series is equal to 0.

Remove anomalies based on STL decomposition.  Provide the absolute value of mean difference of the initial 37th observation and the imputed value rounded with 3 decimal digits as an answer.

You can load the tsAirgap data set in R by issuing the following command at the console data("tsAirgap") after importing "imputeTS" library or if you use other programming languages you can download it [here](https://github.com/SteffenMoritz/imputeTS/blob/master/data/tsAirgap.rda).



Solution
========

You can use time_decompose() %>% anomalize(remainder) %>% time_recompose() and clean_anomalies() functions.

Meta-information
================
exname:  Processing 1
extype: num
exsolution: `r sol_round`
extol: 0.01